In [140]:
import pandas as pd

import numpy as np
__author__ = "Thierry Barros"

df = pd.read_csv("dados.csv", encoding="utf-8", header=None)

df.rename(columns={0: 'Source', 1: 'Target', 2: 'Rating',3:'Time'}, inplace=True)

df1 = df[df['Rating']>=8]

df1.to_csv('dados1.csv')


tam = df1['Source'].max()

matrix = np.zeros((tam,tam), dtype=np.float64)

print matrix

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [141]:
link = {}

for i in df1.Source:
    link[i] = len(df1[df1['Source']==i])


for i in link.keys():
    target = df1[df1['Source']==i]
    for j in target.Target:
        matrix[i-1][j-1] = (1.0/link[i])

        
    

In [142]:
a = np.zeros((tam,tam), dtype=np.float64)
a[0:tam, 0:tam] = 1
a = np.matrix(a)
b = (float(1)/float(tam))*a
print b

[[0.00016669 0.00016669 0.00016669 ... 0.00016669 0.00016669 0.00016669]
 [0.00016669 0.00016669 0.00016669 ... 0.00016669 0.00016669 0.00016669]
 [0.00016669 0.00016669 0.00016669 ... 0.00016669 0.00016669 0.00016669]
 ...
 [0.00016669 0.00016669 0.00016669 ... 0.00016669 0.00016669 0.00016669]
 [0.00016669 0.00016669 0.00016669 ... 0.00016669 0.00016669 0.00016669]
 [0.00016669 0.00016669 0.00016669 ... 0.00016669 0.00016669 0.00016669]]


In [143]:
m = 0.85*matrix + 0.15*b

In [144]:
c = np.zeros((tam,1), dtype=np.float64)
c[0:tam] = 1
v = (float(1)/float(tam))*c
v = np.matrix(v)
print v

[[0.00016669]
 [0.00016669]
 [0.00016669]
 ...
 [0.00016669]
 [0.00016669]
 [0.00016669]]


In [145]:
count = 0

In [146]:
def pagerank(v):
    global count
    if sum(abs(m*v-v))>0.001:
        count+=1
        print 'count:',count
        print m*v
        print "sum(abs(m*v-v)):",sum(abs(m*v-v))
        return pagerank(m*v)
    else:
        count+=1
        print 'count:',count
        print m*v
        print "sum(abs(m*v-v)):",sum(abs(m*v-v))
        return m*v


In [147]:
result = pagerank(v)

count: 1
[[1.66694449e-04]
 [1.66694449e-04]
 [2.50041674e-05]
 ...
 [2.50041674e-05]
 [2.50041674e-05]
 [1.66694449e-04]]
sum(abs(m*v-v)): [[0.75336723]]
count: 2
[[1.25959540e-04]
 [8.09478291e-05]
 [6.16684711e-06]
 ...
 [6.16684711e-06]
 [6.16684711e-06]
 [2.74203894e-05]]
sum(abs(m*v-v)): [[0.14049669]]
count: 3
[[7.95494417e-05]
 [4.60846541e-05]
 [2.65384435e-06]
 ...
 [2.65384435e-06]
 [2.65384435e-06]
 [7.89566440e-06]]
sum(abs(m*v-v)): [[0.03945527]]
count: 4
[[5.39305786e-05]
 [2.75911307e-05]
 [1.66729826e-06]
 ...
 [1.66729826e-06]
 [1.66729826e-06]
 [3.92306596e-06]]
sum(abs(m*v-v)): [[0.01831951]]
count: 5
[[3.69857809e-05]
 [1.76128226e-05]
 [1.20923420e-06]
 ...
 [1.20923420e-06]
 [1.20923420e-06]
 [2.62643772e-06]]
sum(abs(m*v-v)): [[0.0115516]]
count: 6
[[2.58915548e-05]
 [1.18290268e-05]
 [9.20396127e-07]
 ...
 [9.20396127e-07]
 [9.20396127e-07]
 [1.94824520e-06]]
sum(abs(m*v-v)): [[0.00822111]]
count: 7
[[1.86851330e-05]
 [8.12761418e-06]
 [7.14834175e-07]
 ...
 [7

In [148]:
value = []
for i in sorted(result,reverse=True):
    print i

[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578e-05]]
[[2.03825578

[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758

[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758

[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758

[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758e-07]]
[[1.29407758